### ISSUE TITLE
Can't run katoolin in CentOS 7 

### ISSUE THREAD

**Issue by leiferdjango** [LionSec/katoolin#151]
Hello,

I trying to run katoolin on CentOS 7 x86_64ver, I followed the steps everything is in the right directory, I select options 1 , 2 then I get this error.

Screenshot Attached
![error-katoolin](https://user-images.githubusercontent.com/42446502/44231838-6272d480-a16d-11e8-8af0-d00b94d5571d.png)

**Comment by Fr4nci** [comment]
Hi @leiferdjango ,

your problem derives from the fact that you possess CentOS and now calm I will explain you everything. Every distro has a tool to install the packets, in this case Kali Linux has apt-get and apt; while CentOS, if I am not wrong, it possesses yum. Then you now have two possibilities: or to install Kali Linux and I dissuade you him because I see that don't have a lot of familiarity with the commands of the terminal of Linux, or you install a distro that posside an one tool to install the packets equal to Kali, in this case Ubuntu and his derive are the simplest. In alternative, even if long and boring, you should install yourself one to one the packets. Don't even think however about trying to install apt since your system is shaped for the use of yum.

There is no way to install some packets of apt, since the various tools for the installation of packets have different methods to compile and to install the packets

**Comment by leiferdjango** [comment]
It is ok  my friend my English is not very good either,  but I understand. I will install another version of Linux based in Debian, I think should work. Thanks a lot.
